-- DropForeignKey
ALTER TABLE "PC" DROP CONSTRAINT "PC_userId_fkey";

-- AddForeignKey
ALTER TABLE "PC" ADD CONSTRAINT "PC_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
